config/routes.rb
Rails.application.routes.draw do
  get 'home/index'

  get 'users/index'

  resources :dishes do
    resources :commends
    get :show_comment
    resources :likes do
      get :like
    end
  end
  get "/list_top" , to: "dishes#list_dish_top"
  get "/list_dish", to: "dishes#list_dish"
  get "/post", to: "dishes#post_dish"
  post "/post/new_post", to: "dishes#create_post"
  devise_for :users
  resources :foods
  resources :days
  resources :categories
  resources :users
  post "commends/create", to:"commends#create" 

  post "users/create", to: "users#create"

  root 'home#index'

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :dishs
  has_many :comments
  belongs_to :role

  validates :name, :email, presence: true
  validates :name, length: { minimum: 2 }
  def self.xu_ly_edit(params)
    # binding.pry
    if User.find_by_id(params[:id])
       User.find_by_id(params[:id]).update(name: params[:name], email: params[:email],role_id: params[:role_id])
    # binding.pry
    end
  end
    def self.Them(params)
    # binding.pry
      User.new(name: params[:name], email: params[:email],role_id: params[:role_id],password: params[:password] )
  end
  def islog?
        if self.id.nil? 
          false
        else
          if User.find_by_email(self.email)
            true
          else
            false
          end
        end
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  load_and_authorize_resource
  rescue_from CanCan::AccessDenied do |exception|
   redirect_to root_url, :alert => exception.message
  end 
   before_action :set_user, only: [:show, :edit, :update, :destroy]
  def index
    @users= User.all
    @users=@users.paginate(:page => params[:page], :per_page  => 5)
  end
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_index_path, notice: 'User was successfully destroyed.' }
    end
  end

  def show
  end
  def new
   @users= User.new
  end
  def edit
  end
  def update
    # binding.pry
    respond_to do |format|
      if @user.update(name: user_params[:name], email: user_params[:email],role_id: user_params[:role_id])
        format.html { redirect_to @user, notice: 'user was successfully updated.' }
      else
        format.html { render :edit }
      end
    end
  end
  def create
    @users = User.Them(user_params)
    # binding.pry
    respond_to do |format|
      if @users.save
        format.html { redirect_to users_index_path, notice: 'user was successfully created.' }
      else
        format.html { render :new}
      end
    end
  end

  def set_user
      @user = User.find(params[:id])
  end
  def user_params
    params.require(:user).permit(:id, :name, :email, :role_id, :password)
  end
  
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_form.html.erb
<div style="width:25%; margin-left:35%;">
<%= form_for(@user,  class: "form-signin") do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% @user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
 <div class="field">
    <br><%= f.label :id %>
    <%= params[:id] %>
     <%=f.hidden_field :id, :value=>params[:id] %>
  </div>

  <div class="field">
    <br><%= f.label :name %><br>
    <%= f.text_field :name, class: "form-control" %>
  </div>

  <div class="field">
    <br><%= f.label :email %><br>
    <%= f.email_field :email, class: "form-control" %><br>
  </div>
  <br><%= f.label :Role %><br>
  <%=f.collection_select :role_id, Role.name_role_all, :id, :name, class: "form-control"%>
  <div class="actions">
   <br>
 <br>
    <%= f.submit(:class  => "btn btn-primary") %>
  </div>

<% end %>
</div>

app/views/users/edit.html.erb
<h1>Editing user</h1>
<%= render 'form' %>
<%= link_to 'Back', users_index_path %>

app/views/users/index.html.erb
<h1>List Users</h1>

<%= link_to 'New',new_user_path %>
<table class="table table-bordered">
<thead>
<tr>
<td>ID</td>
<td>Name</td>
<td>Email</td>
<td>Role</td>
<td></td>
<td></td>
<td></td>
</tr>
</thead>
<tbody>
<% @users.each do |user| %>
<tr>
<td><%= user.id %></td>
<td><%= user.name %></td>
<td><%= user.email %></td>
<td><%= Role.name_role(user.role_id) %></td>
<td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
<td><%= link_to 'Show', user %></td>
<td><%= link_to 'Edit', edit_user_path(user.id) %></td>
</tr>
<%end%>
</tbody>
</table>
<%= will_paginate @users %>

app/views/users/new.html.erb
<div style="width:25%; margin-left:35%;">
<h2>new user</h2>
<%= form_for @users, :url =>  users_create_path, class: "form-signin" do |f|%> 
  <% if @users.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@users.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% @users.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name, class: "form-control" %>
  </div>
  <div class="field">
    <%= f.label :email %><br />
    <%= f.email_field :email, class: "form-control" %>
  </div>

   <br><%= f.label :Role %><br>
  <%=f.collection_select :role_id, Role.name_role_all, :id, :name%>
  
  <div class="field">
    <%= f.label :password %>
    <% if @minimum_password_length %>
    <em>(<%= @minimum_password_length %> characters minimum)</em>
    <% end %><br />
    <%= f.password_field :password, class: "form-control"  %>
  </div>

  <div class="actions">
    <%= f.submit "New user",class: "btn btn-primary" %>
  </div>
<% end %>

<%= link_to 'Back', users_index_path %>

app/views/users/show.html.erb
<br> <br> <br>
<style>
	#show{
		font-size: 15px
	}
</style>
<div style="font-size: 15px; width:25%; margin-left:35%;">
<p id="show">
  <strong>Name:</strong>
  <%= @user.name %>
</p>
<p id="show">
   <strong>Email:</strong>
  <%= @user.email %>
</p>
<p id="show">
   <strong>Role:</strong>
  <%= Role.name_role(@user.role_id)%>
</p>
<%= link_to 'Back', users_index_path %>
</div>