config/routes.rb
Rails.application.routes.draw do
  get 'home/index'

  get 'users/index'

  resources :dishes do
    resources :commends
    get :show_comment
    resources :likes do
      get :like
    end
  end
  get "/list_top" , to: "dishes#list_dish_top"
  get "/list_dish", to: "dishes#list_dish"
  get "/post", to: "dishes#post_dish"
  post "/post/new_post", to: "dishes#create_post"
  devise_for :users
  resources :foods
  resources :days
  resources :categories
  resources :users
  post "commends/create", to:"commends#create" 

  post "users/create", to: "users#create"

  root 'home#index'

end

app/models/dish.rb
class Dish < ActiveRecord::Base

  mount_uploader :image, PictureUploader
  belongs_to :food
  belongs_to :category
  has_many :commends
  has_many :dishs_days
   has_many :likes
  has_many :days, through: :dishs_day
  belongs_to :user

  validates :name,:desc,:processing, presence: true
  # validates :desc, inclusion: { in: %w(small medium large), message: "%{value} is not a valid size" }, allow_nil: true
  # validates :name, length: { is: 5, message: "%{value} is not a valid size"  }, allow_blank: true
  def self.list_foods
    Food.all
  end
  def self.top
    # binding.pry
    select('*' )
    joins(:likes).
    group('id').
    order('COUNT(likes.dish_id) DESC').
    limit(8)
  end
  def self.list_categories
    Category.all
  end
  def self.list_dish_slide
    # Dish.find([1, 3]) 
    all=Dish.all
    return all[(Random.rand(all.length))]
  end

  def self.thuc_don
    @sang=Dish.joins(:dishs_days).where("dishs_days.day_id= '1'")
    @trua=Dish.joins(:dishs_days).where("dishs_days.day_id= '2'")
    @toi=Dish.joins(:dishs_days).where("dishs_days.day_id= '4'")
    ran1= Random.rand(@sang.length)
    ran2= Random.rand(@trua.length)
    ran3= Random.rand(@toi.length)
    buasang=@sang[ran1]
    buatrua=Array.new
    buatoi=Array.new
    # binding.pry
    i=0
    while !(buatrua & buatoi).empty?||buatrua.empty?||buatoi.empty?&&(i<=10)
    mon1= @trua[Random.rand(@trua.length)]
    mon2= @trua[Random.rand(@trua.length)]
    mon3= @trua[Random.rand(@trua.length)]
    j=0
    while (mon1==mon2||mon2==mon3||mon3==mon1)&&(j<=10)
    mon1= @trua[Random.rand(@trua.length)]
    mon2= @trua[Random.rand(@trua.length)]
    mon3= @trua[Random.rand(@trua.length)]
    j=j+1
    end
    buatrua=[mon1,mon2,mon3]
   
    mon4= @toi[Random.rand(@toi.length)]
    mon5= @toi[Random.rand(@toi.length)]
    mon6= @toi[Random.rand(@toi.length)]
    k=0
    while (mon4==mon5||mon5==mon6||mon4==mon6)&&(k<=10)
    mon4= @toi[Random.rand(@toi.length)]
    mon5= @toi[Random.rand(@toi.length)]
    mon6= @toi[Random.rand(@toi.length)]
    k=k+1
    end
    buatoi=[mon4,mon5,mon6]
    i=i+1
     end
    thucdon=Hash.new 
    thucdon={ :sang => buasang,:trua => buatrua,:toi => buatoi }
    # binding.pry
    return thucdon 
  end
  
end

app/controllers/dishes_controller.rb
class DishesController < ApplicationController
  load_and_authorize_resource
  rescue_from CanCan::AccessDenied do |exception|
   redirect_to root_url, :alert => exception.message
  end 

  before_action :set_dish, only: [:show, :edit, :update, :destroy]

  # GET /dishes
  # GET /dishes.json
  def index
    @dishes = Dish.all
    @dishes=@dishes.paginate(:page => params[:page], :per_page  => 5)
  end

  def list_dish_top
    # binding.pry
    @dishes= Dish.top
  end
  def list_dish
    if params[:q].blank?&&params[:category_id].blank?
      @dishes = Dish.all
    elsif params[:category_id].blank?   
       @dishes = Dish.where("name LIKE '%#{params[:q]}%'")
    else
      @dishes = Dish.where("category_id = '#{params[:category_id]}'")
    end
    @dishes=@dishes.paginate(:page => params[:page], :per_page  => 12)
  end
  def show_comment
    @dish = Dish.find(params[:dish_id])
  end

  # GET /dishes/new
  def new
    @dish = Dish.new
  end
  def post_dish
    @dish = Dish.new
  end

  # GET /dishes/1/edit
  def edit
  end

  # POST /dishes
  # POST /dishes.json
  def create
    # binding.pry
    @dish = Dish.new(dish_params)

    respond_to do |format|
      if @dish.save
          params[:dish][:id].each do |fa|
          unless fa.blank? or fa.nil?
            DishsDay.create(day_id: fa, dish_id: @dish.id)
          end
        end
        format.html { redirect_to dishes_url, notice: 'Dish was successfully created.' }
      else
        format.html { render :new }
      end
    end
  end
  def create_post
    # binding.pry
    @dish = Dish.new(dish_params)

    respond_to do |format|
      if @dish.save
          params[:dish][:id].each do |fa|
          unless fa.blank? or fa.nil?
            DishsDay.create(day_id: fa, dish_id: @dish.id)
          end
        end
        format.html { redirect_to dish_show_comment_path(@dish.id), notice: 'Dish was successfully created.' }
      else
        format.html { render :post_dish }
      end
    end
  end
  # PATCH/PUT /dishes/1
  # PATCH/PUT /dishes/1.json
  def update
    respond_to do |format|
      if @dish.update(dish_params)
        format.html { redirect_to dishes_url, notice: 'Dish was successfully updated.' }
      else
        format.html { render :edit }
      end
    end
  end

  # DELETE /dishes/1
  # DELETE /dishes/1.json
  def destroy
    @dish.destroy
    respond_to do |format|
      format.html { redirect_to dishes_url, notice: 'Dish was successfully destroyed.' }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_dish
      @dish = Dish.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def dish_params
      # binding.pry
      params.require(:dish).permit(:name, :image, :desc, :processing, :food_id, :id, :category_id, :address)
    end
end

app/helpers/dishes_helper.rb
module DishesHelper
end

app/views/dishes/_form.html.erb
<div id="form">
<%= form_for @dish, :html => {:multipart => true, :class => 'form-horizontal'} do |f| %>
  <% if @dish.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@dish.errors.count, "error") %> prohibited this dish from being saved:</h2>

      <ul>
      <% @dish.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :name,'Tên món ăn:', class: 'col-sm-2 control-label' %><br>
     <div class="col-sm-6">
    <%= f.text_field :name, class: 'form-control'%>
  </div>
  </div>
   <div class="form-group">
    <%= f.label :image,'Hình ảnh:', class: 'col-sm-2 control-label' %><br>
     <div class="col-sm-6">
   <%= f.file_field :image %>
  </div>
  </div>
  <div class="form-group">
    <%= f.label :desc,'Mô tả:', class: 'col-sm-2 control-label' %><br>
     <div class="col-sm-6">
    <%= f.text_area :desc, class: 'form-control' %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :processing,'Phương pháp che bien:', class: 'col-sm-2 control-label' %><br>
     <div class="col-sm-6">
    <%= f.text_area :processing, class: 'form-control' %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :food_id,'Thành phần chính:', class: 'col-sm-2 control-label' %><br>
     <div class="col-sm-6">
    <%=f.collection_select :food_id, Dish.list_foods, :id, :food_name, class: 'form-control'%>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :category_id,'Loại:', class: 'col-sm-2 control-label' %><br>
     <div class="col-sm-6">
    <%=f.collection_select :category_id, Dish.list_categories, :id, :name, class: 'form-control'%>
    </div>
  </div>
  <div class="form-group">
   <%= f.label :Buoi,'Buổi:', class: 'col-sm-2 control-label' %><br>
    <div class="col-sm-6">
    <%= f.collection_check_boxes(:id, Day.all, :id, :day_name) do |b| %>
    <%= b.label(class: "check_box") do %>
      <%= b.check_box %>
      <%= b.object.day_name %>
      <% end %>
    <% end %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :address, class: 'col-sm-2 control-label' %><br>
     <div class="col-sm-6">
    <%= f.text_field :address, class: 'form-control' %>
    </div>
  </div>
  <div class="link">
  <div class="actions">
    <%= f.submit nil, :class => "btn btn-sm btn-success" %>
  </div>
  </div>
<% end %>
</div>

app/views/dishes/_form_dish.html.erb
<div style="width:45%; margin-left:30%;">
<%= form_for @dish, url: post_new_post_path, :html => {:multipart => true}, id:"main-contact-form", class: "form-horizontal" do |f| %>
  <% if @dish.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@dish.errors.count, "error") %> prohibited this dish from being saved:</h2>

      <ul>
      <% @dish.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :name,'Tên món ăn:' %><br>
    <%= f.text_field :name, class: "form-control" %>
  </div>
  <div class="form-group">
    <%= f.label :image, 'Hình ảnh:' %><br>
   <%= f.file_field :image, class: "form-control" %>
  </div>
  <div class="form-group">
    <%= f.label :desc, 'Mô tả:' %><br>
    <%= f.text_area :desc,  class: "form-control" %>
  </div>
  <div class="form-group">
    <%= f.label :processing,'Phương pháp chế biến:' %><br>
    <%= f.text_area :processing, class: "form-control" %>
  </div>
  <div class="form-group">
    <%= f.label :food_id, 'Thành phần chính:' %><br>
    <%=f.collection_select :food_id, Dish.list_foods, :id, :food_name, class: "form-control"%>
  </div>
  <div class="form-group">
    <%= f.label :category_id, 'Loại:' %><br>
    <%=f.collection_select :category_id, Dish.list_categories, :id, :name, class: "form-control"%>
  </div>
  <div>
   <%= f.label :Buoi, 'Buổi:' %><br>
    <%= f.collection_check_boxes(:id, Day.all, :id, :day_name, class: "form-control") do |b| %>
    <%= b.label(class: "check_box") do %>
      <%= b.check_box %>
      <%= b.object.day_name %>
      <% end %>
    <% end %>
  </div>
  <div class="form-group">
    <%= f.label :address %><br>
    <%= f.text_field :address, class: "form-control" %>
  </div>
  <div class="actions">
    <%= f.submit nil, :class => "btn btn-sm btn-success" %>
  </div>
<% end %>
</div>

app/views/dishes/edit.html.erb
<h1>Editing Dish</h1>

<%= render 'form' %>

<%= link_to 'Show', @dish %> |
<%= link_to 'Back', dishes_path %>

app/views/dishes/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Dishes</h1>

<table class="table table-bordered">
<thead>
    <tr>
      <th>Name</th>
      <th>Image</th>
      <th>Desc</th>
      <th>Processing</th>
      <th>Food</th>
      <th>Category</th>
      <th>Address</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @dishes.each do |dish| %>
      <tr>
        <td><%= dish.name %></td>
        <td><img style="width: 200px; height: 90px" class="img-responsive" src="<%=dish.image%>" ></td>
        <td><%= dish.desc %></td>
        <td><%= dish.processing %></td>
        <td><%= dish.food_id %></td>
        <td><%= dish.category_id %></td>
        <td><%= dish.address %></td>
        <td><%= link_to 'Show', dish_show_comment_path(dish.id) %></td>
        <td><%= link_to 'Edit', edit_dish_path(dish) %></td>
        <td><%= link_to 'Destroy', dish, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>
<%= will_paginate @dishes %>
<br>

<%= link_to 'New Dish', new_dish_path %>

app/views/dishes/list_dish.html.erb
<%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
 <section id="portfolio">
        <div class="container">
            <div class="center">
               <h2>Danh Mục Tất Cả Món Ăn </h2>
            </div>
         
            <ul class="portfolio-filter text-center">
                <li><a class="btn btn-default active" href="#" data-filter="*">All Dish</a></li>
               <%Food.all.each do |food|%>
                <li><a class="btn btn-default" href="#" data-filter=".<%=food.id%>"><%=food.food_name%></a></li>
              <%end%>
            </ul><!--/#portfolio-filter-->
                <form id="searchbox" method="get" action="/list_dish">
                <input id="inputsearch" name="q" type="text" size="15" placeholder="Type here..." />
                <input id="button-submit" type="submit" value="Search" />
                </form>
                  <div class="form-group">
                     <%= form_tag '/list_dish',id: "form_category",method: "get", multipart: true do %>
                      <label id="label_category">Loại:</label> 
                      <%= select_tag "category_id", options_from_collection_for_select(Dish.list_categories, "id", "name", params[:category_id].to_i), onchange: 'this.form.submit()', id: "section_category", :include_blank => 'All categories' %>
                      </div>
                    <% end %>
            
            <div class="row">
            <div class="portfolio-items">
             <% @dishes.each do |dss|%>
                <div class="portfolio-item <%=dss.food_id%> bootstrap col-xs-12 col-sm-4 col-md-3">
                    <div class="recent-work-wrap">
                        <img style="width: 300px; height:290px"  class="img-responsive" src="<%=dss.image%>" alt="s">
                        <div class="overlay">
                            <div class="recent-work-inner">
                                <h3><%= link_to dss.name, dish_show_comment_path(dss.id) %> </h3>
                                <p><%=dss.desc%></p>
                               <a class="preview" href="<%=dss.image.to_s%>" rel="prettyPhoto"> View</a>
                            </div> 
                        </div>
                    </div>
                </div>    
             <%end%>
             </div>
                </div>
            </div>
        <div id="phantrang"><%= will_paginate @dishes %></div>
        </div>
    </section><!--/#portfolio-item-->

app/views/dishes/list_dish_top.html.erb
<%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
 <section id="portfolio">
        <div class="container">
            <div class="center">
               <h2>Danh Mục Món Ăn Được Like Nhiều Nhất </h2>
            </div>
         
            <ul class="portfolio-filter text-center">
                <li><a class="btn btn-default active" href="#" data-filter="*">All Dish</a></li>
                <%Food.all.each do |food|%>
                <li><a class="btn btn-default" href="#" data-filter=".<%=food.id%>"><%=food.food_name%></a></li>
                <%end%>
            </ul><!--/#portfolio-filter-->
            
            <div class="row">
            <div class="portfolio-items">
             <% @dishes.each do |dss|%>
                <div class="portfolio-item <%=dss.food_id%> bootstrap col-xs-12 col-sm-4 col-md-3">
                    <div class="recent-work-wrap">
                        <img style="width: 300px; height:290px"  class="img-responsive" src="<%=dss.image%>" alt="s">
                        <div class="overlay">
                            <div class="recent-work-inner">
                                <h3><%= link_to dss.name, dish_show_comment_path(dss.id) %> </h3>
                                <p><%=dss.desc%></p>
                               <a class="preview" href="<%=dss.image.to_s%>" rel="prettyPhoto"> View</a>
                            </div> 
                        </div>
                    </div>
                </div>    
             <%end%>
             </div>
                </div>
            </div>
        </div>
    </section><!--/#portfolio-item-->

app/views/dishes/new.html.erb
<h1>New Dish</h1>

<%= render 'form' %>

<%= link_to 'Back', dishes_path %>

app/views/dishes/post_dish.html.erb
<br><br><br>
<h2 style="text-align: center;" >Thêm Món Ăn</h2>

<%= render 'form_dish' %>
 <div class="link2">
<%= link_to 'Back', dishes_path %>
</div>

app/views/dishes/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @dish.name %>
</p>

<p>
  <strong>Image:</strong>
  <%= image_tag(@dish.image_url, :width => 600) if @dish.image.present? %>
</p>

<p>
  <strong>Desc:</strong>
  <%= @dish.desc %>
</p>

<p>
  <strong>Processing:</strong>
  <%= @dish.processing %>
</p>

<p>
  <strong>Food:</strong>
  <%= @dish.food_id %>
</p>

<p>
  <strong>Category:</strong>
  <%= @dish.category_id %>
</p>

<p>
  <strong>Address:</strong>
  <%= @dish.address %>
</p>

<h2>Comments</h2>
<% @dish.commends.each do |comment| %>
  <td><td><strong><%= User.find_by(id: comment.user_id).name %>:</strong>
  <%= comment.comment %><br>
  <% if current_user.present?%>
  <%= link_to 'Remove', [@dish,comment], method: :delete, data: { confirm: 'Are you sure?' } if current_user.role_id==1 or current_user && current_user.id == comment.user_id %><br>
  <%end%>
<% end %>
<% if current_user.present?%>
  <h2>Add a comment:</h2>
   <%= form_for([@dish, @dish.commends.build]) do |f| %>
    <p>
      <%= f.label :comment%><br>
      <%= f.text_area :comment %>
    </p>   
    <p><%= f.submit %></p>
  <% end %>
<% else%>
  <p><%= link_to "Please sign in to comment!", new_user_session_path%><p>
<% end%>
<%= link_to 'Back', dishes_path %>

app/views/dishes/show_comment.html.erb
<%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
<br> <br><br>
<div class="post_comment">
  <h2 style="text-align: center; color: #666666; font-size: 30px;"><%= @dish.name %></h2>

  <%= image_tag(@dish.image_url, :width => 600, id: "image") if @dish.image.present? %>

<p>
  <strong>Mô tả:</strong>
  <%= @dish.desc %>
</p>

<p>
  <strong>Phương pháp:</strong>
  <%= @dish.processing %>
</p>

<p>
  <strong>Thành phần chính:</strong>
  <%= Food.find_by_id(@dish.food_id).food_name %>
</p>

<p>
  <strong>Loại:</strong>
  <%= Category.find_by_id(@dish.category_id).name %>
</p>

<p>
  <strong>Địa Chỉ Gợi Ý:</strong>
  <%= @dish.address %>
</p>
 <div id="panel">
      <input id="address" type="textbox" value="<%=@dish.address%>">
      <input type="button" value="Geocode" onclick="codeAddress()">
    </div>
    <div id="map-canvas">
    <script type="text/javascript"> initialize(); </script>
    </div>
</div>
<div id="reviews">
 <%= render :partial => @dish.commends %>
</div>

<% if current_user.present?%>
  <%if Like.find_by(like: 1, user_id: current_user.id, dish_id: @dish.id).nil?%>
  <div class="Like_dish">
  <%= link_to 'Thích', dish_like_like_path(@dish.id, current_user.id, :format => :js), id: "like", :remote => true %>
  </div>

  <% else %>
  <div class="Like_dish" id="Like_dishdd">
  <%= link_to 'Liked', :remote => true %>
  </div>
   <% end %>
  <div id="count"><%= Like.where(dish_id: @dish.id).count %></div>
  <div id="comment">
   <%= form_for([@dish, @dish.commends.build]) do |f| %>
    <p>
     <br>
      <%= f.text_area :comment, id: "texarea_comment" %>
    </p>   

    <p><%= f.submit "Create comment",  id: "botton", class: "btn btn-success green" %></p>
  <% end %>
  </div>
<% else%>
  <p class="pleas"><%= link_to "Please sign in to comment and like!", new_user_session_path, class: "text_pleas"%><p>
<% end%>
<div class="black">
<%= link_to 'Back', dishes_path %>
</div>