config/routes.rb
Rails.application.routes.draw do
  get 'home/index'

  get 'users/index'

  resources :dishes do
    resources :commends
    get :show_comment
    resources :likes do
      get :like
    end
  end
  get "/list_top" , to: "dishes#list_dish_top"
  get "/list_dish", to: "dishes#list_dish"
  get "/post", to: "dishes#post_dish"
  post "/post/new_post", to: "dishes#create_post"
  devise_for :users
  resources :foods
  resources :days
  resources :categories
  resources :users
  post "commends/create", to:"commends#create" 

  post "users/create", to: "users#create"

  root 'home#index'

end

app/models/category.rb
class Category < ActiveRecord::Base
  has_many :dishs
  validates :name, presence: true
  validates :name, length: { minimum: 2 }
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  load_and_authorize_resource
  rescue_from CanCan::AccessDenied do |exception|
   redirect_to root_url, :alert => exception.message
  end 
  before_action :set_category, only: [:show, :edit, :update, :destroy]

  # GET /categories
  # GET /categories.json
  def index
    @categories = Category.all
    @category = Category.new
  end

  # GET /categories/1
  # GET /categories/1.json
  def show
  end

  # GET /categories/new
  # def new
  #   @category = Category.new
  # end

  # GET /categories/1/edit
  def edit
  end

  # POST /categories
  # POST /categories.json
  def create
    @category = Category.new(category_params)

    respond_to do |format|
      if @category.save
        format.html { redirect_to categories_url, notice: 'Category was successfully created.' }
      else
        format.html { render :index }
      end
    end
  end

  # PATCH/PUT /categories/1
  # PATCH/PUT /categories/1.json
  def update
    respond_to do |format|
      if @category.update(category_params)
        format.html { redirect_to categories_url, notice: 'Category was successfully updated.' }
      else
        format.html { render :edit }
      end
    end
  end

  # DELETE /categories/1
  # DELETE /categories/1.json
  def destroy
    @category.destroy
    respond_to do |format|
      format.html { redirect_to categories_url, notice: 'Category was successfully destroyed.' }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_category
      @category = Category.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def category_params
      params.require(:category).permit(:name)
    end
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/views/categories/_form.html.erb
<div style="width:25%;">
<%= form_for(@category, class: "form-signin") do |f| %>
  <% if @category.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@category.errors.count, "error") %> prohibited this category from being saved:</h2>

      <ul>
      <% @category.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name, class: "form-control" %>
  </div>
  <div class="actions">
    <%= f.submit class: "btn btn-success"%>
  </div>
<% end %>
</div>

app/views/categories/edit.html.erb
<h1>Editing Category</h1>

<%= render 'form' %>

<%= link_to 'Show', @category %> |
<%= link_to 'Back', categories_path %>

app/views/categories/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Categories</h1>

<table class="table table-bordered">
  <thead>
    <tr>
      <th>Name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @categories.each do |category| %>
      <tr>
        <td><%= category.name %></td>
        <td><%= link_to 'Edit', edit_category_path(category) %></td>
        <td><%= link_to 'Destroy', category, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>
<%= render 'form' %>

app/views/categories/new.html.erb
<h1>New Category</h1>

<%= render 'form' %>
<div class="link2">
<%= link_to 'Back', categories_path %>
</div>