config/routes.rb
Rails.application.routes.draw do
  get 'home/index'

  get 'users/index'

  resources :dishes do
    resources :commends
    get :show_comment
    resources :likes do
      get :like
    end
  end
  get "/list_top" , to: "dishes#list_dish_top"
  get "/list_dish", to: "dishes#list_dish"
  get "/post", to: "dishes#post_dish"
  post "/post/new_post", to: "dishes#create_post"
  devise_for :users
  resources :foods
  resources :days
  resources :categories
  resources :users
  post "commends/create", to:"commends#create" 

  post "users/create", to: "users#create"

  root 'home#index'

end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    # Define abilities for the passed in user here. For example:
    #
    #   user ||= User.new # guest user (not logged in)
    #   if user.admin?
    #     can :manage, :all
    #   else
    #     can :read, :all
    #   end
    #
    # The first argument to `can` is the action you are giving the user
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on.
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details:
    # https://github.com/CanCanCommunity/cancancan/wiki/Defining-Abilities
    user ||= User.new
    # binding.pry
    if user.islog?
     # binding.pry
        can :manage, :all if user.role.name == "admin"
        can :post_dish, :all
        can :show_comment, :all
        can :create_post, :all
        can :list_dish, :all
        can :list_dish_top, :all
    else
        can :show_comment, :all
        can :list_dish, :all
        can :list_dish_top, :all
        # cannot :new , :user_id => user.id

    end
  end
end

app/models/category.rb
class Category < ActiveRecord::Base
  has_many :dishs
  validates :name, presence: true
  validates :name, length: { minimum: 2 }
end

app/models/commend.rb
class Commend < ActiveRecord::Base
  belongs_to :user
  belongs_to :dishs

end

app/models/day.rb
class Day < ActiveRecord::Base
  has_many :dishs_day
  has_many :dishs, :through => :dishs_day
end

app/models/dish.rb
class Dish < ActiveRecord::Base

  mount_uploader :image, PictureUploader
  belongs_to :food
  belongs_to :category
  has_many :commends
  has_many :dishs_days
   has_many :likes
  has_many :days, through: :dishs_day
  belongs_to :user

  validates :name,:desc,:processing, presence: true
  # validates :desc, inclusion: { in: %w(small medium large), message: "%{value} is not a valid size" }, allow_nil: true
  # validates :name, length: { is: 5, message: "%{value} is not a valid size"  }, allow_blank: true
  def self.list_foods
    Food.all
  end
  def self.top
    # binding.pry
    select('*' )
    joins(:likes).
    group('id').
    order('COUNT(likes.dish_id) DESC').
    limit(8)
  end
  def self.list_categories
    Category.all
  end
  def self.list_dish_slide
    # Dish.find([1, 3]) 
    all=Dish.all
    return all[(Random.rand(all.length))]
  end

  def self.thuc_don
    @sang=Dish.joins(:dishs_days).where("dishs_days.day_id= '1'")
    @trua=Dish.joins(:dishs_days).where("dishs_days.day_id= '2'")
    @toi=Dish.joins(:dishs_days).where("dishs_days.day_id= '4'")
    ran1= Random.rand(@sang.length)
    ran2= Random.rand(@trua.length)
    ran3= Random.rand(@toi.length)
    buasang=@sang[ran1]
    buatrua=Array.new
    buatoi=Array.new
    # binding.pry
    i=0
    while !(buatrua & buatoi).empty?||buatrua.empty?||buatoi.empty?&&(i<=10)
    mon1= @trua[Random.rand(@trua.length)]
    mon2= @trua[Random.rand(@trua.length)]
    mon3= @trua[Random.rand(@trua.length)]
    j=0
    while (mon1==mon2||mon2==mon3||mon3==mon1)&&(j<=10)
    mon1= @trua[Random.rand(@trua.length)]
    mon2= @trua[Random.rand(@trua.length)]
    mon3= @trua[Random.rand(@trua.length)]
    j=j+1
    end
    buatrua=[mon1,mon2,mon3]
   
    mon4= @toi[Random.rand(@toi.length)]
    mon5= @toi[Random.rand(@toi.length)]
    mon6= @toi[Random.rand(@toi.length)]
    k=0
    while (mon4==mon5||mon5==mon6||mon4==mon6)&&(k<=10)
    mon4= @toi[Random.rand(@toi.length)]
    mon5= @toi[Random.rand(@toi.length)]
    mon6= @toi[Random.rand(@toi.length)]
    k=k+1
    end
    buatoi=[mon4,mon5,mon6]
    i=i+1
     end
    thucdon=Hash.new 
    thucdon={ :sang => buasang,:trua => buatrua,:toi => buatoi }
    # binding.pry
    return thucdon 
  end
  
end

app/models/dishs_day.rb
class DishsDay < ActiveRecord::Base
  belongs_to :dish
  belongs_to :day
end

app/models/food.rb
class Food < ActiveRecord::Base
  has_many :dishs
end

app/models/like.rb
class Like < ActiveRecord::Base
    belongs_to :dish
end

app/models/role.rb
class Role < ActiveRecord::Base
  has_many :users
  
  def self.name_role(id)
    Role.find_by_id(id).name
  end
  def self.name_role_all
    Role.all
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :dishs
  has_many :comments
  belongs_to :role

  validates :name, :email, presence: true
  validates :name, length: { minimum: 2 }
  def self.xu_ly_edit(params)
    # binding.pry
    if User.find_by_id(params[:id])
       User.find_by_id(params[:id]).update(name: params[:name], email: params[:email],role_id: params[:role_id])
    # binding.pry
    end
  end
    def self.Them(params)
    # binding.pry
      User.new(name: params[:name], email: params[:email],role_id: params[:role_id],password: params[:password] )
  end
  def islog?
        if self.id.nil? 
          false
        else
          if User.find_by_email(self.email)
            true
          else
            false
          end
        end
    end
end

app/controllers/days_controller.rb
class DaysController < ApplicationController
  load_and_authorize_resource
  rescue_from CanCan::AccessDenied do |exception|
   redirect_to root_url, :alert => exception.message
  end 
  before_action :set_day, only: [:show, :edit, :update, :destroy]

  # GET /days
  # GET /days.json
  def index
    @days = Day.all
    @day = Day.new
  end

  # GET /days/1
  # GET /days/1.json
  def show
  end

  # GET /days/new
  # def new
  #   @day = Day.new
  # end

  # GET /days/1/edit
  def edit
  end

  # POST /days
  # POST /days.json
  def create
    @day = Day.new(day_params)

    respond_to do |format|
      if @day.save
        format.html { redirect_to days_url, notice: 'Day was successfully created.' }
      else
        format.html { render :index }
      end
    end
  end

  # PATCH/PUT /days/1
  # PATCH/PUT /days/1.json
  def update
    respond_to do |format|
      if @day.update(day_params)
        format.html { redirect_to days_url, notice: 'Day was successfully updated.' }
      else
        format.html { render :edit }
      end
    end
  end

  # DELETE /days/1
  # DELETE /days/1.json
  def destroy
    @day.destroy
    respond_to do |format|
      format.html { redirect_to days_url, notice: 'Day was successfully destroyed.' }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_day
      @day = Day.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def day_params
      params.require(:day).permit(:day_name)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/commends_helper.rb
module CommendsHelper
end

app/helpers/days_helper.rb
module DaysHelper
end

app/helpers/dishes_helper.rb
module DishesHelper
end

app/helpers/foods_helper.rb
module FoodsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/__application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>SharePicturesDish</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<% if notice %>
  <p class="alert alert-success"><%= notice %></p>
<% end %>
<% if alert %>
  <p class="alert alert-danger"><%= alert %></p>

<% end %>
<p class="navbar-text pull-right">
<% if user_signed_in? %>
  Logged in as <strong><%= current_user.email %></strong>.
  <%= link_to 'Edit profile', edit_user_registration_path, :class => 'navbar-link' %> |
  <%= link_to "Logout", destroy_user_session_path, method: :delete, :class => 'navbar-link'  %>
<% else %>
  <%= link_to "Sign up", new_user_registration_path, :class => 'navbar-link'  %> |
  <%= link_to "Login", new_user_session_path, :class => 'navbar-link'  %>
<% end %>
<%= yield %>
</p>
</body>
</html>

app/views/layouts/_footer.html.erb
 <section id="middle">
        <div class="container">
            <div class="row">
                <div class="col-sm-6 wow fadeInDown">
                    <div class="skill">
                        <h2>Tỉ lệ dinh dưỡng trong khẩu phần khuyên dùng.</h2>
                

                        <div class="progress-wrap">
                            <h3>Chất đường</h3>
                            <div class="progress">
                              <div class="progress-bar  color1" role="progressbar" aria-valuenow="40" aria-valuemin="0" aria-valuemax="100" style="width: 55%">
                                <span class="bar-width">55%</span>
                              </div>

                            </div>
                        </div>

                        <div class="progress-wrap">
                            <h3>Chất đạm</h3>
                            <div class="progress">
                              <div class="progress-bar color2" role="progressbar" aria-valuenow="20" aria-valuemin="0" aria-valuemax="100" style="width: 40%">
                               <span class="bar-width">40%</span>
                              </div>
                            </div>
                        </div>

                        <div class="progress-wrap">
                            <h3>Chất béo</h3>
                            <div class="progress">
                              <div class="progress-bar color3" role="progressbar" aria-valuenow="60" aria-valuemin="0" aria-valuemax="100" style="width: 25%">
                                <span class="bar-width">25%</span>
                              </div>
                            </div>
                        </div>

                        <div class="progress-wrap">
                            <h3>Khoáng chất, Vitamin</h3>
                            <div class="progress">
                              <div class="progress-bar color4" role="progressbar" aria-valuenow="80" aria-valuemin="0" aria-valuemax="100" style="width: 2%">
                                <span class="bar-width">2%</span>
                              </div>
                            </div>
                        </div>
                    </div>

                </div><!--/.col-sm-6-->

                <div class="col-sm-6 wow fadeInDown">
                    <div class="accordion">
                        <h2>Thực phẩm cực tốt cho hệ tiêu hóa</h2>
                        <div class="panel-group" id="accordion1">
                          <div class="panel panel-default">
                            <div class="panel-heading active">
                              <h3 class="panel-title">
                                <a class="accordion-toggle" data-toggle="collapse" data-parent="#accordion1" href="#collapseOne1">
                                  Gừng - chữa đầy hơi, khó tiêu
                                  <i class="fa fa-angle-right pull-right"></i>
                                </a>
                              </h3>
                            </div>

                            <div id="collapseOne1" class="panel-collapse collapse in">
                              <div class="panel-body">
                                  <div class="media accordion-inner">
                                        <div class="pull-left">
                                            <img style="width:80px; height:80px" class="img-responsive" src="assets/gg.jpg">
                                        </div>
                                        <div class="media-body">
                                             
                                             <p>Gừng từ lâu đã được đánh giá cao vì khả năng điều trị các vấn đề khác nhau của đường tiêu hóa. Gừng có thể chữa trị một cách hiệu quả các vấn đề như: đầy hơi và trướng bụng, khó tiêu, co thắt dạ dày và buồn nôn hoặc ốm nghén. Nó cũng có đặc tính kháng viêm và kháng khuẩn mạnh mẽ có thể hỗ trợ sức khỏe đường tiêu hóa</p>
                                        </div>
                                  </div>
                              </div>
                            </div>
                          </div>

                          <div class="panel panel-default">
                            <div class="panel-heading">
                              <h3 class="panel-title">
                                <a class="accordion-toggle" data-toggle="collapse" data-parent="#accordion1" href="#collapseTwo1">
                                   Bạc hà cay - dùng để điều trị các bệnh về tiêu hóa
                                  <i class="fa fa-angle-right pull-right"></i>
                                </a>
                              </h3>
                            </div>
                            <div id="collapseTwo1" class="panel-collapse collapse">
                              <div class="panel-body">
                                Loại thảo mộc này cũng được sử dụng trong nhiều thế kỷ để điều trị các bệnh tiêu hóa khác nhau. Tính làm mát của nó có thể giúp làm dịu xuống một số rối loạn dạ dày và thúc đẩy chữa bệnh đường tiêu hóa. Nó cũng có đặc tính chống viêm và khử trùng.
                            </div>
                          </div>

                          <div class="panel panel-default">
                            <div class="panel-heading">
                              <h3 class="panel-title">
                                <a class="accordion-toggle" data-toggle="collapse" data-parent="#accordion1" href="#collapseThree1">
                                  Sữa chua - giảm tiêu chảy, táo bón
                                  <i class="fa fa-angle-right pull-right"></i>
                                </a>
                              </h3>
                            </div>
                            <div id="collapseThree1" class="panel-collapse collapse">
                              <div class="panel-body">
                                Do có hàm lượng probiotic cao,sữa chualà một trong những thực phẩm tốt nhất cho việc nâng cao hiệu quả và sức khỏe của hệ tiêu hóa. Ăn sữa chua sẽ giúp cơ thể bạn tiêu hóa hiệu quả hơn và nó có thể làm giảm nguy cơ tiêu chảy, táo bón và chứng khó tiêu.
                              </div>
                            </div>
                          </div>

                          <div class="panel panel-default">
                            <div class="panel-heading">
                              <h3 class="panel-title">
                                <a class="accordion-toggle" data-toggle="collapse" data-parent="#accordion1" href="#collapseFour1">
                                  Khoai lang - chữa chứng viêm loét dạ dày, tá tràng
                                  <i class="fa fa-angle-right pull-right"></i>
                                </a>
                              </h3>
                            </div>
                            <div id="collapseFour1" class="panel-collapse collapse">
                              <div class="panel-body">
                                Khoai langchứa lượng vitamin, khoáng chất, chất xơ và carbohydrate cao. Do đó, nó là một lựa chọn tuyệt vời hệ tiêu hóa. Khoai lang được biết đến với khả năng chữa chứng viêm loét dạ dày, tá tràng và có thể giúp ngăn ngừa các gốc tự do.
                              </div>
                            </div>
                          </div>
                        </div><!--/#accordion1-->
                    </div>
                </div>

            </div><!--/.row-->
        </div><!--/.container-->
    </section><!--/#middle-->

<div class="navbar navbar-default navbar-bottom" >
    <footer id="footer" class="midnight-blue">
        <div class="container">
            <div class="row">
                <div class="col-sm-6">
                    &copy; 2013 <a target="_blank" href="http://shapebootstrap.net/" title="Free Twitter Bootstrap WordPress Themes and HTML templates">ShapeBootstrap</a>. All Rights Reserved.
                </div>
                <div class="col-sm-6">
                    <ul class="pull-right">
                        <li><a href="#">Home</a></li>
                        <li><a href="#">About Us</a></li>
                        <li><a href="#">Faq</a></li>
                        <li><a href="#">Contact Us</a></li>
                    </ul>
                </div>
            </div>
        </div>
    </footer><!--/#footer-->
<div id="fb-root"></div>
<script>(function(d, s, id) {
  var js, fjs = d.getElementsByTagName(s)[0];
  if (d.getElementById(id)) return;
  js = d.createElement(s); js.id = id;
  js.src = "//connect.facebook.net/vi_VN/sdk.js#xfbml=1&version=v2.3";
  fjs.parentNode.insertBefore(js, fjs);
}(document, 'script', 'facebook-jssdk'));</script>
<div style=" background: #EEEEEE; width: 16%; margin-left: 80%; " class="navbar navbar-inner  navbar-fixed-bottom">
<div class="container">
<div class="fb-like" data-href="http://daotao.dut.udn.vn/sv/" data-layout="button_count" data-action="like" data-show-faces="true" data-share="true"></div>
</div>
</div>
</div>
</body>
</html>

app/views/layouts/_header.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="">
    <meta name="author" content="">
    <title>Home | Corlate</title>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
	<!-- core CSS -->
    <link href="bootstrap.min.css" rel="stylesheet">
    <link href="font-awesome.min.css" rel="stylesheet">
    <link href="animate.min.css" rel="stylesheet">
    <link href="prettyPhoto.css" rel="stylesheet">
    <link href="main.css" rel="stylesheet">
    <link href="responsive.css" rel="stylesheet">
    <!--[if lt IE 9]>
    <script src="js/html5shiv.js"></script>
    <script src="js/respond.min.js"></script>
    <![endif]-->
    <script src="assets/jquery.js"></script>
    <script src="assets/bootstrap.min.js"></script>
    <script src="assets/jquery.prettyPhoto.js"></script>
    <script src="assets/jquery.isotope.min.js"></script>
    <script src="assets/main.js"></script>
    <script src="assets/wow.min.js"></script>
    <script src="https://maps.googleapis.com/maps/api/js?libraries=geometry"></script>
    <script src="https://maps.googleapis.com/maps/api/js?v=3.exp&signed_in=true"></script>
    <link rel="shortcut icon" href="<%= asset_path "ico/favicon.ico" %>">
    <link rel="apple-touch-icon-precomposed" sizes="144x144" href=" <%= asset_path "ico/apple-touch-icon-144-precomposed.png" %>">
    <link rel="apple-touch-icon-precomposed" sizes="114x114" href=" <%= asset_path "ico/apple-touch-icon-114-precomposed.png" %>">
    <link rel="apple-touch-icon-precomposed" sizes="72x72" href="<%= asset_path "ico/apple-touch-icon-72-precomposed.png" %>">
    <link rel="apple-touch-icon-precomposed" href="<%= asset_path "ico/apple-touch-icon-57-precomposed.png" %>">
</head><!--/head-->

<body class="homepage">

    <header id="header">
        <div class="top-bar">
            <div class="container">
                <div class="row">
                    <div class="col-sm-6 col-xs-4">
                        <div class="top-number"><p><i class="fa fa-phone-square"></i>  +0123 456 70 90</p></div>
                    </div>
                    <div class="col-sm-6 col-xs-8">
                       <div class="social">
                            <ul class="social-share">
                                <li><a href="#"><i class="fa fa-facebook"></i></a></li>
                                <li><a href="#"><i class="fa fa-twitter"></i></a></li>
                                <li><a href="#"><i class="fa fa-linkedin"></i></a></li> 
                                <li><a href="#"><i class="fa fa-dribbble"></i></a></li>
                                <li><a href="#"><i class="fa fa-skype"></i></a></li>
                            </ul>
                            <div class="search">
                                <form role="form">
                                    <input type="text" class="search-form" autocomplete="off" placeholder="Search">
                                    <i class="fa fa-search"></i>
                                </form>
                           </div>
                       </div>
                    </div>
                </div>
            </div><!--/.container-->
        </div><!--/.top-bar-->

        <nav class="navbar navbar-inverse navbar-fixed-top wet-asphalt" role="banner">
        <p class="navbar-text pull-right">
            <% if user_signed_in? %>
              Logged in as <strong><%= current_user.email %></strong>.
              <%= link_to 'Edit profile', edit_user_registration_path, :class => 'navbar-link' %> |
              <%= link_to "Logout", destroy_user_session_path, method: :delete, :class => 'navbar-link'  %>
            <% else %>
              <%= link_to "Sign up", new_user_registration_path, :class => 'navbar-link'  %> |
              <%= link_to "Login", new_user_session_path, :class => 'navbar-link'  %>
            <% end %></p>
            <div class="container">
                <div class="navbar-header">
                    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                        <span class="sr-only">Toggle navigation</span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>
                    <a class="navbar-brand" href="/">
                    <%=image_tag("logo.png")%></a>
                </div>
				
                <div id="menu" class="collapse navbar-collapse navbar-right">
                    <ul class="nav navbar-nav">
                        <li><%= link_to 'Trang Chủ', root_path %></li>
                        <li><%= link_to 'Thêm món ăn', post_path %></li>
                        <li><%= link_to 'Top 8 like', list_top_path %></li>
                        <li><%= link_to 'Danh sách món ăn', list_dish_path %></li>
                    <% if current_user.present?&&(current_user.role_id==1)%>
                        <li class="dropdown">
                            <a href="#" class="dropdown-toggle" data-toggle="dropdown">Quản Lý</a>
                            <ul class="dropdown-menu">
                                <li><%= link_to 'Danh sách user ', users_path %></li>
                                <li><%= link_to 'Danh sách dishes ', dishes_path %></li>
                                <li><%= link_to 'Danh sách categories ', categories_path %></li>
                                <li><%= link_to 'Danh sách Thực Phẩm ', foods_path %></li>
                            </ul>
                        </li>
                    <%end%>
                        <li><a href="blog.html">Blog</a></li> 
                        <li><a href="contact-us.html">Contact</a></li>                        
                    </ul>
                </div>

            </div><!--/.container-->
        </nav><!--/nav-->
		
    </header><!--/header-->

app/views/layouts/_slide.html.erb
    
<style>
.post-body img {
box-shadow: 0px 0px 15px #000; /* Shadow */
border-radius: 50%; /* Rounded border */
border:0;
padding:0;
-moz-transition: all 1s;
-webkit-transition: all 1s;
-o-transition: all 1s;
}
.post-body img:hover {
box-shadow: 0; /* With this we remove the shadow (value 0) */
border-radius: 0; /* This removes the border roundness (value 0) */
-moz-transition: all 1s;
-webkit-transition: all 1s;
-o-transition: all 1s;
cursor:pointer;

}
.img-responsive{width: 100%; height: 100%}
</style>
    <section id="main-slider" class="no-margin">
        <div class="carousel slide">
            <ol class="carousel-indicators">
                <li data-target="#main-slider" data-slide-to="0" class="active"></li>
                <li data-target="#main-slider" data-slide-to="1"></li>
                <li data-target="#main-slider" data-slide-to="2"></li>
            </ol>
            <div class="carousel-inner">

                <div class="item active" style="background-image: url(<%= asset_path "slider/bg1.jpg" %>);">
                    <div class="container">
                        <div class="row slide-margin">
                            <div class="col-sm-6">
                                <div class="carousel-content">
                                <%@dish1=Dish.list_dish_slide%>
                                    <h1 class="animation animated-item-1"><%=@dish1.name%></h1>
                                    <h2 class="animation animated-item-2"><%=@dish1.desc%>...</h2>                               
                                </div>
                            </div>
                            <div class="col-sm-6 hidden-xs animation animated-item-4">
                                <div class="post-body">
                                    <img src="<%= @dish1.image%>" class="img-responsive">
                                </div>                               
                            </div>

                        </div>
                    </div>
                </div><!--/.item-->

                <div class="item" style="background-image: url(<%= asset_path "slider/bg2.jpg" %>)">
                    <div class="container">
                        <div class="row slide-margin">
                            <div class="col-sm-6">
                                <div class="carousel-content">
                                 <%@dish2=Dish.list_dish_slide%>
                                    <h1 class="animation animated-item-1"><%=@dish2.name%></h1>
                                    <h2 class="animation animated-item-2"><%=@dish2.desc%>...</h2>                                
                                </div>
                            </div>
                            <div class="col-sm-6 hidden-xs animation animated-item-4">
                                <div class="post-body">
                                    <img src="<%= @dish2.image%>" class="img-responsive">
                                </div>                              
                            </div>

                        </div>
                    </div>
                </div><!--/.item-->

                <div class="item" style="background-image: url(<%= asset_path "slider/bg3.jpg" %>)">
                   <div class="container">
                        <div class="row slide-margin">
                            <div class="col-sm-6">
                                <div class="carousel-content">
                                <%@dish3=Dish.list_dish_slide%>
                                    <h1 class="animation animated-item-1"><%=@dish3.name%></h1>
                                    <h2 class="animation animated-item-2"><%=@dish3.desc%>...</h2>                                
                                </div>
                            </div>
                            <div class="col-sm-6 hidden-xs animation animated-item-4">
                                <div class="post-body">
                                    <img src="<%= @dish3.image%>" class="img-responsive">
                                </div>                               
                            </div>
                        </div>
                    </div>
                </div><!--/.item-->
            </div><!--/.carousel-inner-->
        </div><!--/.carousel-->
        <a class="prev hidden-xs" href="#main-slider" data-slide="prev">
            <i ><<</i>
        </a>
        <a class="next hidden-xs" href="#main-slider" data-slide="next">
            <i > >> </i>
        </a>
    </section><!--/#main-slider-->

app/views/layouts/application.html.erb
<%= render 'layouts/header' %>

<br> <br>

<%= yield %>

<%= render 'layouts/footer' %>